### ISSUE TITLE
WARN: Can't find a 'libwebp/1.0.0@bincrafters/stable' package for the specified settings

### ISSUE THREAD

**Issue by hxzj** [anibali/pywebp#11]
`conanfile.txt: Installing package
Requirements
    libwebp/1.0.0@bincrafters/stable from 'conan-center' - Cache
Packages
    libwebp/1.0.0@bincrafters/stable:dce9a1cf9dc0bd09e307a9ca8e7627a21c9cef80 - Missing

libwebp/1.0.0@bincrafters/stable: WARN: Can't find a 'libwebp/1.0.0@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.version=4.8, os=Linux
- Options: fPIC=True, near_lossless=True, shared=False, swap_16bit_csp=False, with_simd=True
- Dependencies: 
- Package ID: dce9a1cf9dc0bd09e307a9ca8e7627a21c9cef80

Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'License :: OSI Approved :: MIT License',
  File "/usr/local/python3/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/python3/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/python3/lib/python3.7/site-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/local/python3/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/local/python3/lib/python3.7/site-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/hua.cao/webp-0.1.0a13/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/hua.cao/webp-0.1.0a13/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/hua.cao/webp-0.1.0a13/.eggs/cffi-1.12.3-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "webp_build/builder.py", line 14, in <module>
    conan.install(path=getcwd(), cwd=tmp_dir)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/conan_api.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/conan_api.py", line 560, in install
    no_imports=no_imports)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/manager.py", line 80, in install
    installer.install(deps_graph, remotes, keep_build=keep_build, graph_info=graph_info)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/installer.py", line 307, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/installer.py", line 319, in _build
    out=output, recorder=self._recorder)
  File "/usr/local/python3/lib/python3.7/site-packages/conans/client/installer.py", line 287, in raise_package_not_found_error
    ''' % (ref, ref.name))
conans.errors.ConanException: Missing prebuilt package for 'libwebp/1.0.0@bincrafters/stable'
Try to build it from sources with "--build libwebp"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"`

**Comment by anibali** [comment]
I think your GCC version is too old (4.8). It looks like the earliest prebuilt package provided by [conan-libwebp](https://github.com/bincrafters/conan-libwebp) is for GCC 4.9.
